### ISSUE TITLE
Custom plugin config syntax is not supported

### ISSUE THREAD

**Issue by wzyboy** [LaunchPlatform/beancount-parser#11]
Beancount allows passing custom config (a literal string that will be parsed by `ast.literal_eval()`) to a plugin. This syntax is not currected supported by beancount-parser.

Minimal reproducible example:

```
plugin "plugins.zerosum" "{
  'zerosum_accounts': {
    'Equity:Transfers': ('Equity:Transfers:Matched', 7),
  },
  'flag_unmatched': True
}"
```

Stack trace:

```
INFO:beancount_black.main:Processing file plugin.bean
Traceback (most recent call last):
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/lark/lexer.py", line 536, in lex
    token = self.root_lexer.next_token(lexer_state, parser_state)
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/lark/lexer.py", line 466, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches '"' in the current parser context, at line 1 col 26

plugin "plugins.zerosum" "{
                         ^
Expected one of: 
	* FLAG
	* SIGNED_NUMBER
	* _NL
	* COMMENT
	* "@@"
	* HASH
	* ACCOUNT
	* BOOLEAN
	* "{{"
	* TAG
	* COLON
	* _EMPTY_LINE
	* TAGS
	* RBRACE
	* CURRENCY
	* METADATA_KEY
	* LBRACE
	* LINK
	* "}}"
	* DATE
	* AT
	* COMMA
	* ESCAPED_STRING
	* SECTION_HEADER

Previous tokens: Token('ESCAPED_STRING', '"plugins.zerohosted zonesum"')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wzyboy/.local/bin/bean-black", line 8, in <module>
    sys.exit(main())
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/beancount_black/main.py", line 47, in main
    tree = parser.parse(input_content)
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/lark/lark.py", line 625, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 188, in parse_from_state
    raise e
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 178, in parse_from_state
    for token in state.lexer.lex(state):
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/lark/lexer.py", line 539, in lex
    raise e  # Raise the original UnexpectedCharacters. The root lexer raises it with the wrong expected set.
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/lark/lexer.py", line 528, in lex
    yield lexer.next_token(lexer_state, parser_state)
  File "/home/wzyboy/.local/pipx/venvs/beancount-black/lib/python3.10/site-packages/lark/lexer.py", line 466, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches '"' in the current parser context, at line 1 col 26

plugin "plugins.zerosum" "{
                         ^
Expected one of: 
	* ESCAPED_STRING
	* _NL
	* COMMENT

Previous tokens: Token('ESCAPED_STRING', '"plugins.zerosum"')

```

**Comment by fangpenlin** [comment]
Hey @wzyboy thanks for reporting the bug!

Yeah, you are right, currently multi-lines is not supported. I am using Lark's [ESCAPED_STRING](https://github.com/lark-parser/lark/blob/8a77e42c83a034cf19e86f755013f8a432f36c79/lark/grammars/common.lark#L26-L29), and it doesn't look like support multi-line text. I guess it shouldn't be a hard fix as long as I change the regex to include newline char. Will look into this and fix it shortly when I have time.

**Comment by fangpenlin** [comment]
@wzyboy the issue has already been addressed.
