### ISSUE TITLE
Newline at beginning of file: Unexpected token Token('_NL', '\n') at line 1, column 1

### ISSUE THREAD

**Issue by tbm** [LaunchPlatform/beancount-parser#4]
I think this is different to #3 but it also relates to tags.  Specifically, tags on the same line as the txn header:

I'm not sure why it's getting confused here.

```
INFO:beancount_black.main:Processing file d
Traceback (most recent call last):
  File "/home/tbm/.local/lib/python3.9/site-packages/lark/lexer.py", line 528, in lex
    yield lexer.next_token(lexer_state, parser_state)
  File "/home/tbm/.local/lib/python3.9/site-packages/lark/lexer.py", line 466, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches '
' in the current parser context, at line 1 col 1


^
Expected one of: 
	* METADATA_KEY
	* ACCOUNT
	* FLAG
	* DATE
	* SECTION_HEADER
	* COMMENT
...

lark.exceptions.UnexpectedToken: Unexpected token Token('_NL', '\n') at line 1, column 1.
Expected one of: 
	* OPTION
	* METADATA_KEY
	* INCLUDE
	* ACCOUNT
	* FLAG
	* DATE
	* $END
	* SECTION_HEADER
	* PLUGIN
	* COMMENT
Previous tokens: [None]
```

Test case:

```
2000-01-01 open Assets:Cash
2000-01-01 open Equity:Opening-Balance

2022-01-01 * "Opening balance: cash" #opening-balance
  Assets:Cash                                              10.00 EUR
  Equity:Opening-Balance
```

**Comment by tbm** [comment]
No, it's not related to tags.  Removing the tag doesn't help.

I can't figure out why it gets confused.

This passes bean-check:

```
2000-01-01 open Assets:Cash
2000-01-01 open Equity:OpeningBalance

2022-01-01 * "Test"
  Assets:Cash                                    10.00 EUR
  Equity:OpeningBalance
```

**Comment by tbm** [comment]
Huh, the problem is that my test file has an empty line at the beginning, i.e.:

```

2000-01-01 open Assets:Cash
2000-01-01 open Equity:OpeningBalance

2022-01-01 * "Test"
  Assets:Cash                                    10.00 EUR
  Equity:OpeningBalance
```

This is perfectly valid.

**Comment by fangpenlin** [comment]
Just realized that if you put multiple empty lines ahead there will still be error
